import { rawCategories } from "./categories";
import { rawSources } from "./sources";
import { validateAtlasData, type Descriptor, type RangeScore } from "./schema";

const draftSource = "coffee-flavor-atlas-editorial-pilot";

const score = (min: number, typical: number, max: number): RangeScore => ({
  min,
  typical,
  max,
});

export const rawDescriptors = [
  {
    id: "jasmine",
    slug: "jasmine",
    labels: { en: "Jasmine", zhHans: "茉莉" },
    aliases: {
      en: ["jasmine flower", "white floral", "tea flower"],
      zhHans: ["茉莉花", "白花香", "茶花感"],
    },
    categoryId: "floral",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A lifted white-flower association that can feel clean, airy, and tea-like rather than sugary.",
      zhHans: "一种轻盈的白花联想，常显得干净、通透，并带有近似花茶的气息。",
    },
    sensoryAssociation: {
      sourness: score(0.8, 1.5, 2.4),
      sweetness: score(1.2, 2.1, 3),
      bitterness: score(0, 0.5, 1.2),
      aromaProminence: score(3.4, 4.5, 5),
      body: score(0.4, 1.1, 2),
      roastFermentation: score(0, 0.5, 1.3),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "star-petal",
      density: 0.72,
      curvature: 0.82,
      halo: 0.46,
      motion: "bloom",
    },
  },
  {
    id: "rose",
    slug: "rose",
    labels: { en: "Rose", zhHans: "玫瑰" },
    aliases: {
      en: ["rose petal", "pink floral", "floral perfume"],
      zhHans: ["玫瑰花", "花瓣感", "粉色花香"],
    },
    categoryId: "floral",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A rounded floral association with a soft perfume edge and a gentle impression of sweetness.",
      zhHans: "圆润的花香联想，带一点柔和香氛边缘，也容易让人感到轻微甜意。",
    },
    sensoryAssociation: {
      sourness: score(0.6, 1.2, 2.1),
      sweetness: score(1.5, 2.5, 3.4),
      bitterness: score(0, 0.6, 1.4),
      aromaProminence: score(3, 4.1, 5),
      body: score(0.8, 1.5, 2.5),
      roastFermentation: score(0, 0.6, 1.4),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "folded-petal",
      density: 0.68,
      curvature: 0.9,
      halo: 0.5,
      motion: "breathe",
    },
  },
  {
    id: "orange-blossom",
    slug: "orange-blossom",
    labels: { en: "Orange Blossom", zhHans: "橙花" },
    aliases: {
      en: ["citrus blossom", "neroli-like", "orange flower"],
      zhHans: ["柑橘花", "橙花香", "橙树花"],
    },
    categoryId: "floral",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A bridge between blossom and citrus peel, usually brighter and more sparkling than rose.",
      zhHans: "连接花香与柑橘皮的联想，通常比玫瑰更明亮，也更有清爽感。",
    },
    sensoryAssociation: {
      sourness: score(1.2, 2.3, 3.3),
      sweetness: score(1.4, 2.3, 3.2),
      bitterness: score(0.1, 0.7, 1.5),
      aromaProminence: score(3.2, 4.2, 5),
      body: score(0.4, 1, 1.9),
      roastFermentation: score(0, 0.5, 1.2),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "citrus-petal",
      density: 0.64,
      curvature: 0.78,
      halo: 0.44,
      motion: "drift",
    },
  },
  {
    id: "bellflower",
    slug: "bellflower",
    labels: { en: "Bellflower", zhHans: "钟形花" },
    aliases: {
      en: ["campanula", "bell flower", "unresolved floral"],
      zhHans: ["风铃草", "钟花", "待验证花香"],
    },
    categoryId: "unresolved",
    descriptorStatus: "unresolved",
    sensoryModalities: ["orthonasal"],
    summary: {
      en: "A placeholder floral candidate kept visible to test how uncertain vocabulary behaves in the Atlas.",
      zhHans:
        "一个保留在图谱中的花香候选词，用来测试不确定词汇在界面中的呈现方式。",
    },
    sensoryAssociation: {
      sourness: score(0.5, 1.2, 2.2),
      sweetness: score(0.8, 1.7, 2.8),
      bitterness: score(0, 0.7, 1.7),
      aromaProminence: score(1.4, 2.5, 3.8),
      body: score(0.3, 0.9, 1.8),
      roastFermentation: score(0, 0.4, 1.3),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "open-bell",
      density: 0.4,
      curvature: 0.72,
      halo: 0.34,
      motion: "echo",
    },
    editorialNote: {
      en: "This term is intentionally unresolved; the MVP does not claim it is a stable coffee descriptor.",
      zhHans: "该词刻意标为待验证；本版本不声称它已经是稳定的咖啡描述词。",
    },
  },
  {
    id: "lemon",
    slug: "lemon",
    labels: { en: "Lemon", zhHans: "柠檬" },
    aliases: {
      en: ["lemon peel", "citrus acid", "yellow citrus"],
      zhHans: ["柠檬皮", "柠檬酸感", "黄色柑橘"],
    },
    categoryId: "fruit",
    descriptorStatus: "canonical",
    sensoryModalities: ["taste", "orthonasal", "retronasal"],
    summary: {
      en: "A bright citrus association with high sourness and a clean aromatic edge.",
      zhHans: "明亮的柑橘联想，酸感关联较高，香气边缘清晰。",
    },
    sensoryAssociation: {
      sourness: score(3.4, 4.4, 5),
      sweetness: score(0.5, 1.4, 2.4),
      bitterness: score(0.2, 0.9, 1.8),
      aromaProminence: score(2.5, 3.6, 4.6),
      body: score(0.2, 0.8, 1.6),
      roastFermentation: score(0, 0.3, 1),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "citrus-slice",
      density: 0.62,
      curvature: 0.54,
      halo: 0.35,
      motion: "bloom",
    },
  },
  {
    id: "orange",
    slug: "orange",
    labels: { en: "Orange", zhHans: "橙" },
    aliases: {
      en: ["sweet orange", "orange peel", "citrus"],
      zhHans: ["甜橙", "橙皮", "柑橘"],
    },
    categoryId: "fruit",
    descriptorStatus: "canonical",
    sensoryModalities: ["taste", "orthonasal", "retronasal"],
    summary: {
      en: "A citrus association that balances rounded sweetness with moderate acidity.",
      zhHans: "一种在圆润甜感和中等酸感之间取得平衡的柑橘联想。",
    },
    sensoryAssociation: {
      sourness: score(2.2, 3.2, 4.2),
      sweetness: score(1.8, 2.9, 4),
      bitterness: score(0.2, 0.8, 1.7),
      aromaProminence: score(2.6, 3.7, 4.7),
      body: score(0.5, 1.3, 2.2),
      roastFermentation: score(0, 0.4, 1.2),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "segment",
      density: 0.58,
      curvature: 0.62,
      halo: 0.4,
      motion: "breathe",
    },
  },
  {
    id: "blueberry",
    slug: "blueberry",
    labels: { en: "Blueberry", zhHans: "蓝莓" },
    aliases: {
      en: ["blue fruit", "berry", "ripe blueberry"],
      zhHans: ["蓝色浆果", "浆果", "成熟蓝莓"],
    },
    categoryId: "fruit",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "taste"],
    summary: {
      en: "A darker berry association with sweetness, acidity, and a rounded aromatic center.",
      zhHans: "较深色的浆果联想，兼具甜、酸与圆润的香气中心。",
    },
    sensoryAssociation: {
      sourness: score(1.8, 2.8, 3.8),
      sweetness: score(2.4, 3.5, 4.5),
      bitterness: score(0.1, 0.6, 1.4),
      aromaProminence: score(2.8, 4, 5),
      body: score(1, 2, 3.1),
      roastFermentation: score(0.2, 0.9, 1.8),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "berry-cluster",
      density: 0.8,
      curvature: 0.5,
      halo: 0.42,
      motion: "drift",
    },
  },
  {
    id: "red-berries",
    slug: "red-berries",
    labels: { en: "Red Berries", zhHans: "红色浆果" },
    aliases: {
      en: ["red berry", "raspberry-like", "cranberry-like", "mixed red fruit"],
      zhHans: ["红浆果", "覆盆子感", "蔓越莓感", "红色水果"],
    },
    categoryId: "fruit",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "taste"],
    summary: {
      en: "A generalized red-fruit node for tart, vivid berry associations without naming a single fruit.",
      zhHans:
        "一个泛化的红色水果节点，用于表达明亮、偏酸的浆果联想，而不指定单一水果。",
    },
    sensoryAssociation: {
      sourness: score(2.6, 3.6, 4.6),
      sweetness: score(1.7, 2.7, 3.8),
      bitterness: score(0.1, 0.6, 1.5),
      aromaProminence: score(2.6, 3.8, 4.8),
      body: score(0.8, 1.7, 2.7),
      roastFermentation: score(0.1, 0.7, 1.6),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "small-berry-spray",
      density: 0.86,
      curvature: 0.48,
      halo: 0.5,
      motion: "bloom",
    },
    editorialNote: {
      en: "This is a broad pilot node. Later versions should decide whether to split it into named berry descriptors.",
      zhHans:
        "这是一个泛化试验节点。后续版本需要判断是否拆分成更具体的浆果描述词。",
    },
  },
  {
    id: "dried-fruit",
    slug: "dried-fruit",
    labels: { en: "Dried Fruit", zhHans: "干果" },
    aliases: {
      en: ["raisin", "date-like", "dried plum", "dark fruit"],
      zhHans: ["葡萄干", "枣感", "果干", "深色水果"],
    },
    categoryId: "fruit",
    descriptorStatus: "compound",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A concentrated fruit association that often feels darker, heavier, and less sharp than fresh fruit.",
      zhHans: "浓缩的水果联想，通常比新鲜水果更深、更厚，也没有那么尖锐。",
    },
    sensoryAssociation: {
      sourness: score(0.9, 1.8, 2.9),
      sweetness: score(2.6, 3.7, 4.7),
      bitterness: score(0.2, 0.9, 1.8),
      aromaProminence: score(2.4, 3.5, 4.4),
      body: score(1.6, 2.8, 4),
      roastFermentation: score(0.8, 1.8, 3),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "wrinkled-oval",
      density: 0.7,
      curvature: 0.58,
      halo: 0.36,
      motion: "echo",
    },
  },
  {
    id: "honey",
    slug: "honey",
    labels: { en: "Honey", zhHans: "蜂蜜" },
    aliases: {
      en: ["floral honey", "syrupy sweetness", "nectar"],
      zhHans: ["花蜜", "蜜感", "蜂蜜甜"],
    },
    categoryId: "sweet",
    descriptorStatus: "canonical",
    sensoryModalities: ["retronasal", "taste", "mouthfeel"],
    summary: {
      en: "A warm sweetness association with floral lift and a soft, syrup-like mouthfeel cue.",
      zhHans: "温暖的甜感联想，带花香上扬，并暗示柔软、糖浆般的口感。",
    },
    sensoryAssociation: {
      sourness: score(0.2, 0.8, 1.7),
      sweetness: score(3.3, 4.3, 5),
      bitterness: score(0, 0.4, 1.1),
      aromaProminence: score(2.2, 3.3, 4.4),
      body: score(1.5, 2.6, 3.7),
      roastFermentation: score(0.2, 0.8, 1.6),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "honeycomb",
      density: 0.7,
      curvature: 0.32,
      halo: 0.42,
      motion: "breathe",
    },
  },
  {
    id: "caramel",
    slug: "caramel",
    labels: { en: "Caramel", zhHans: "焦糖" },
    aliases: {
      en: ["caramelized sugar", "toffee", "burnt sugar"],
      zhHans: ["焦糖化", "太妃糖", "焦糖甜"],
    },
    categoryId: "sweet",
    descriptorStatus: "canonical",
    sensoryModalities: ["retronasal", "taste", "mouthfeel"],
    summary: {
      en: "A browned-sugar association that combines sweetness with roast warmth and gentle bitterness.",
      zhHans: "褐变糖类联想，将甜感、烘烤温度和轻微苦感结合在一起。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.5, 1.3),
      sweetness: score(3, 4.1, 5),
      bitterness: score(0.5, 1.4, 2.5),
      aromaProminence: score(2.2, 3.4, 4.5),
      body: score(1.8, 3, 4.1),
      roastFermentation: score(1.6, 2.8, 4),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "ribbon",
      density: 0.56,
      curvature: 0.8,
      halo: 0.4,
      motion: "bloom",
    },
  },
  {
    id: "brown-sugar",
    slug: "brown-sugar",
    labels: { en: "Brown Sugar", zhHans: "红糖" },
    aliases: {
      en: ["molasses", "raw sugar", "dark sugar"],
      zhHans: ["黑糖", "糖蜜", "深色糖"],
    },
    categoryId: "sweet",
    descriptorStatus: "canonical",
    sensoryModalities: ["retronasal", "taste", "mouthfeel"],
    summary: {
      en: "A darker sugar association with soft sweetness, mild molasses depth, and modest roast warmth.",
      zhHans: "较深色的糖类联想，甜感柔和，带轻微糖蜜厚度和适度烘烤温度。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.4, 1.2),
      sweetness: score(3.2, 4, 4.8),
      bitterness: score(0.3, 1, 2),
      aromaProminence: score(1.8, 2.9, 4),
      body: score(1.8, 2.9, 4),
      roastFermentation: score(1.2, 2.3, 3.6),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "granule",
      density: 0.66,
      curvature: 0.35,
      halo: 0.28,
      motion: "drift",
    },
  },
  {
    id: "almond",
    slug: "almond",
    labels: { en: "Almond", zhHans: "杏仁" },
    aliases: {
      en: ["almond skin", "marzipan", "light nut"],
      zhHans: ["杏仁皮", "杏仁糖", "浅色坚果"],
    },
    categoryId: "nut-cocoa",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A pale nut association that can feel clean, lightly sweet, and gently dry.",
      zhHans: "浅色坚果联想，可能显得干净、微甜，并带一点干爽感。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.5, 1.3),
      sweetness: score(1.1, 2, 3),
      bitterness: score(0.4, 1.1, 2),
      aromaProminence: score(1.8, 2.8, 3.8),
      body: score(1.2, 2.1, 3.2),
      roastFermentation: score(0.8, 1.8, 3),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "seed",
      density: 0.52,
      curvature: 0.64,
      halo: 0.25,
      motion: "breathe",
    },
  },
  {
    id: "hazelnut",
    slug: "hazelnut",
    labels: { en: "Hazelnut", zhHans: "榛子" },
    aliases: {
      en: ["roasted hazelnut", "nutty", "praline"],
      zhHans: ["烤榛子", "坚果感", "果仁糖"],
    },
    categoryId: "nut-cocoa",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A rounded roasted-nut association with more warmth and body than almond.",
      zhHans: "圆润的烘烤坚果联想，比杏仁更温暖，也更有厚度。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.4, 1.1),
      sweetness: score(1.3, 2.2, 3.2),
      bitterness: score(0.5, 1.3, 2.3),
      aromaProminence: score(2, 3.1, 4.2),
      body: score(1.6, 2.6, 3.7),
      roastFermentation: score(1.2, 2.4, 3.7),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "round-nut",
      density: 0.58,
      curvature: 0.58,
      halo: 0.28,
      motion: "drift",
    },
  },
  {
    id: "dark-chocolate",
    slug: "dark-chocolate",
    labels: { en: "Dark Chocolate", zhHans: "黑巧克力" },
    aliases: {
      en: ["cacao", "bitter chocolate", "cocoa"],
      zhHans: ["可可", "苦巧", "黑巧"],
    },
    categoryId: "nut-cocoa",
    descriptorStatus: "canonical",
    sensoryModalities: ["retronasal", "taste", "mouthfeel"],
    summary: {
      en: "A cacao-like association where bitterness, body, and roast depth become the main cues.",
      zhHans: "可可类联想，苦感、厚度和烘烤深度是主要线索。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.5, 1.4),
      sweetness: score(0.8, 1.7, 2.8),
      bitterness: score(2.4, 3.6, 4.8),
      aromaProminence: score(2.6, 3.7, 4.8),
      body: score(2.4, 3.6, 4.8),
      roastFermentation: score(2.4, 3.6, 4.8),
    },
    confidence: "high",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "cacao-shard",
      density: 0.78,
      curvature: 0.28,
      halo: 0.36,
      motion: "echo",
    },
  },
  {
    id: "cinnamon",
    slug: "cinnamon",
    labels: { en: "Cinnamon", zhHans: "肉桂" },
    aliases: {
      en: ["warm spice", "cinnamon bark", "sweet spice"],
      zhHans: ["暖香料", "桂皮", "甜香料"],
    },
    categoryId: "spice-roasted",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A warm spice association with aromatic sweetness but little direct sourness.",
      zhHans: "温暖香料联想，带香气上的甜意，但直接酸感很低。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.4, 1.2),
      sweetness: score(1.2, 2.2, 3.2),
      bitterness: score(0.4, 1.2, 2.1),
      aromaProminence: score(2.4, 3.6, 4.7),
      body: score(1, 2, 3),
      roastFermentation: score(1, 2.2, 3.5),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "bark-curl",
      density: 0.62,
      curvature: 0.86,
      halo: 0.32,
      motion: "drift",
    },
  },
  {
    id: "tobacco",
    slug: "tobacco",
    labels: { en: "Tobacco", zhHans: "烟草" },
    aliases: {
      en: ["dry tobacco", "leafy tobacco", "cured leaf"],
      zhHans: ["干烟草", "烟叶", "熟化叶片"],
    },
    categoryId: "spice-roasted",
    descriptorStatus: "boundary",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A dry cured-leaf association that sits near roast, wood, and spice rather than fresh greenness.",
      zhHans: "干燥熟化叶片的联想，靠近烘烤、木质和香料，而不是新鲜青绿。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.4, 1.2),
      sweetness: score(0.5, 1.2, 2.2),
      bitterness: score(1.4, 2.5, 3.8),
      aromaProminence: score(2, 3.2, 4.4),
      body: score(1.6, 2.7, 3.9),
      roastFermentation: score(2.2, 3.4, 4.6),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "dry-leaf",
      density: 0.66,
      curvature: 0.6,
      halo: 0.26,
      motion: "echo",
    },
    editorialNote: {
      en: "This boundary term can be culturally sensitive and should be reviewed before public research use.",
      zhHans: "该边界词可能带有文化和语境敏感性，公开研究使用前应重新审阅。",
    },
  },
  {
    id: "smoky",
    slug: "smoky",
    labels: { en: "Smoky", zhHans: "烟熏" },
    aliases: {
      en: ["smoke", "wood smoke", "roast smoke"],
      zhHans: ["烟感", "木烟", "烘烤烟感"],
    },
    categoryId: "spice-roasted",
    descriptorStatus: "boundary",
    sensoryModalities: ["orthonasal", "retronasal"],
    summary: {
      en: "A smoke-linked association that can signal roast, process, or defect depending on context.",
      zhHans:
        "与烟气相关的联想，可能指向烘烤、处理过程或瑕疵，需结合语境判断。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.3, 1.1),
      sweetness: score(0.2, 0.8, 1.8),
      bitterness: score(1.8, 3, 4.4),
      aromaProminence: score(2.4, 3.7, 5),
      body: score(1.5, 2.7, 4),
      roastFermentation: score(3.1, 4.2, 5),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "smoke-thread",
      density: 0.72,
      curvature: 0.88,
      halo: 0.38,
      motion: "drift",
    },
    editorialNote: {
      en: "Smoky can be desirable or undesirable depending on roast and evaluation context; the Atlas does not assign value.",
      zhHans:
        "烟熏感在不同烘焙和评估语境中可能正面也可能负面；本图谱不做价值判断。",
    },
  },
  {
    id: "green-tea",
    slug: "green-tea",
    labels: { en: "Green Tea", zhHans: "绿茶" },
    aliases: {
      en: ["tea-like", "sencha-like", "green infusion"],
      zhHans: ["茶感", "煎茶感", "绿茶香"],
    },
    categoryId: "green-earthy",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "taste"],
    summary: {
      en: "A clean leafy-tea association with gentle bitterness and a quiet aromatic profile.",
      zhHans: "干净的叶片茶感联想，带轻微苦感和安静的香气轮廓。",
    },
    sensoryAssociation: {
      sourness: score(0.4, 1.1, 2),
      sweetness: score(0.4, 1.2, 2.2),
      bitterness: score(0.9, 1.9, 3),
      aromaProminence: score(1.8, 2.9, 4),
      body: score(0.6, 1.4, 2.4),
      roastFermentation: score(0.3, 1, 2),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "tea-leaf",
      density: 0.56,
      curvature: 0.7,
      halo: 0.28,
      motion: "breathe",
    },
  },
  {
    id: "cedar",
    slug: "cedar",
    labels: { en: "Cedar", zhHans: "雪松" },
    aliases: {
      en: ["cedarwood", "dry wood", "pencil cedar"],
      zhHans: ["雪松木", "干木质", "木质香"],
    },
    categoryId: "green-earthy",
    descriptorStatus: "canonical",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A dry aromatic wood association with resin, structure, and light bitterness.",
      zhHans: "干燥芳香木质联想，带树脂感、结构感和轻微苦感。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.5, 1.4),
      sweetness: score(0.3, 0.9, 1.8),
      bitterness: score(1, 2.1, 3.4),
      aromaProminence: score(2, 3.1, 4.2),
      body: score(1.2, 2.2, 3.4),
      roastFermentation: score(1.2, 2.4, 3.7),
    },
    confidence: "medium",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "wood-grain",
      density: 0.64,
      curvature: 0.5,
      halo: 0.22,
      motion: "echo",
    },
  },
  {
    id: "earthy",
    slug: "earthy",
    labels: { en: "Earthy", zhHans: "土壤感" },
    aliases: {
      en: ["soil-like", "humus", "wet earth"],
      zhHans: ["泥土感", "湿土", "土质"],
    },
    categoryId: "green-earthy",
    descriptorStatus: "boundary",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A soil-like association that can read as grounding, rustic, or problematic depending on context.",
      zhHans:
        "接近土壤的联想，可能显得沉稳、质朴，也可能在某些语境中被视为问题。",
    },
    sensoryAssociation: {
      sourness: score(0, 0.5, 1.5),
      sweetness: score(0.1, 0.6, 1.5),
      bitterness: score(1.2, 2.3, 3.6),
      aromaProminence: score(1.8, 3, 4.2),
      body: score(1.8, 3, 4.3),
      roastFermentation: score(1.4, 2.7, 4.1),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "soil-grain",
      density: 0.82,
      curvature: 0.34,
      halo: 0.24,
      motion: "drift",
    },
    editorialNote: {
      en: "Earthy is treated as a boundary descriptor because its meaning changes strongly with culture, roast, and defect framing.",
      zhHans:
        "土壤感被标为边界词，因为它的含义会随文化、烘焙和瑕疵语境显著变化。",
    },
  },
  {
    id: "fermented",
    slug: "fermented",
    labels: { en: "Fermented", zhHans: "发酵感" },
    aliases: {
      en: ["ferment", "cultured", "process-forward"],
      zhHans: ["发酵", "处理感", "培养物感"],
    },
    categoryId: "fermented",
    descriptorStatus: "compound",
    sensoryModalities: ["orthonasal", "retronasal", "taste"],
    summary: {
      en: "A process-linked association that can include fruit lift, cultured sharpness, and aromatic volatility.",
      zhHans:
        "与处理过程相关的复合联想，可能包含水果上扬、培养物般尖锐感和挥发香气。",
    },
    sensoryAssociation: {
      sourness: score(1.6, 2.8, 4.2),
      sweetness: score(0.8, 1.8, 3),
      bitterness: score(0.5, 1.3, 2.4),
      aromaProminence: score(2.8, 4, 5),
      body: score(1.1, 2.2, 3.5),
      roastFermentation: score(3, 4.1, 5),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "bubble-chain",
      density: 0.88,
      curvature: 0.66,
      halo: 0.62,
      motion: "bloom",
    },
    editorialNote: {
      en: "Fermented is intentionally broad here; later validation should separate desirable process notes from off-note language.",
      zhHans:
        "此处的发酵感刻意保持宽泛；后续验证应区分正向处理风味与负面异味语言。",
    },
  },
  {
    id: "winey",
    slug: "winey",
    labels: { en: "Winey", zhHans: "葡萄酒感" },
    aliases: {
      en: ["wine-like", "vinous", "red wine"],
      zhHans: ["酒感", "葡萄酒样", "红酒感"],
    },
    categoryId: "fermented",
    descriptorStatus: "compound",
    sensoryModalities: ["orthonasal", "retronasal", "taste"],
    summary: {
      en: "A compound association of fruit acidity, light fermentation, and a vinous aromatic impression.",
      zhHans: "由水果酸感、轻微发酵和葡萄酒样香气共同组成的复合联想。",
    },
    sensoryAssociation: {
      sourness: score(2.2, 3.3, 4.4),
      sweetness: score(1.2, 2.2, 3.4),
      bitterness: score(0.4, 1.1, 2.1),
      aromaProminence: score(2.8, 3.9, 5),
      body: score(1.2, 2.4, 3.7),
      roastFermentation: score(2.2, 3.5, 4.8),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "wine-arc",
      density: 0.7,
      curvature: 0.76,
      halo: 0.52,
      motion: "echo",
    },
    editorialNote: {
      en: "Winey is marked compound because it mixes fruit, acidity, and fermentation rather than a single sensory cue.",
      zhHans:
        "葡萄酒感标为复合词，因为它混合了水果、酸感和发酵，而不是单一感官线索。",
    },
  },
  {
    id: "cheese",
    slug: "cheese",
    labels: { en: "Cheese", zhHans: "乳酪" },
    aliases: {
      en: ["cheesy", "cultured dairy", "lactic"],
      zhHans: ["奶酪", "乳制品发酵", "乳酸感"],
    },
    categoryId: "fermented",
    descriptorStatus: "boundary",
    sensoryModalities: ["orthonasal", "retronasal", "mouthfeel"],
    summary: {
      en: "A cultured-dairy boundary association included to test how the Atlas handles unstable or polarizing descriptors.",
      zhHans:
        "一种培养乳制品类边界联想，用来测试图谱如何呈现不稳定或分歧较大的描述词。",
    },
    sensoryAssociation: {
      sourness: score(1, 2.1, 3.5),
      sweetness: score(0.1, 0.7, 1.8),
      bitterness: score(0.6, 1.6, 2.9),
      aromaProminence: score(2.4, 3.8, 5),
      body: score(2, 3.3, 4.6),
      roastFermentation: score(3.2, 4.3, 5),
    },
    confidence: "low",
    evidenceStatus: "project_curated_draft",
    sourceIds: [draftSource],
    visualProfile: {
      motif: "culture-cell",
      density: 0.84,
      curvature: 0.42,
      halo: 0.7,
      motion: "breathe",
    },
    editorialNote: {
      en: "Cheese is a boundary prototype, not a recommendation or defect claim. It requires future sensory validation.",
      zhHans:
        "乳酪是边界原型词，不代表推荐也不等同瑕疵结论；后续需要感官验证。",
    },
  },
] satisfies Descriptor[];

const validated = validateAtlasData({
  categories: rawCategories,
  sources: rawSources,
  descriptors: rawDescriptors,
});

export const descriptors = validated.descriptors;

export const descriptorsBySlug = Object.fromEntries(
  descriptors.map((descriptor) => [descriptor.slug, descriptor]),
) as Record<string, Descriptor>;

export const descriptorsById = Object.fromEntries(
  descriptors.map((descriptor) => [descriptor.id, descriptor]),
) as Record<string, Descriptor>;
